Final touches
Meri-MG/Microverse-Student-Project-1 pull request #1
Opened 2021-09-15 18:04 UTC by Meri-MG

2021-09-15 19:48 UTC, barackm requested changes
Hi @Meri-MG, 👋 

You have done an amazing job so far! 👏👏👏
However, there are some issues that you still need to work on to go to the next project. But remember you are almost there 😉  😉 !

# STATUS: Required Changes ♻️
### _Check the comments under the review._ 👇 

- [ ] Kindly let's add a descriptive summary for the Pull request to give an idea of what changes you have introduced 👍 

![](https://media.giphy.com/media/iZKF7CKpEEva2OZE6a/giphy.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

- [x] [OPTIONAL] It's a good idea to always start our commit messages with uppercase letters, let's make better mistakes tomorrow 😉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-15 19:48 UTC, barackm commented on README.md
> +https://meri-mg.github.io/Microverse-Student-Project-1/
- [ ] Kindly let's fix the live demo link since it seems to be broken for now 👇 
![image](https://user-images.githubusercontent.com/55465133/133495184-1abccd87-cf0d-4b05-bb2a-92b8b1d8dbb1.png)

2021-09-15 19:48 UTC, barackm commented on README.md
> +N/A
- [ ] I think it could be a good idea to add instructions on how to set up the project locally, to help non-technical people to know how to do so. 👍

2021-09-15 19:48 UTC, barackm commented on index.html
> +        </nav>
- [ ] You have done a great job using the `<a>` tags for the logo(your name) and the hamburger icon, however, the logo should not be inside the `<nav>` tag since the nav tag is used to have the menu links. Kindly let's remove the logo inside the `<nav>` tag, this will make our code more semantic 😉

2021-09-15 19:48 UTC, barackm commented on index.html
> +    </section>
- [ ] Kindly let's have only one `<section>` tag the headline section because for now, I can see that you have many independent sections.
- [ ] For the Languages, Skills, and Frameworks let us please use the unordered list to group the list of the languages, skills, and frameworks like in the example below 👇 
```
<ul>
   <li>
       Javascript
   </li>
   <li>
       Ruby
   </li>
</ul>
```
Kindly let's fix this issue 👍 

- [ ] Let us do the same for the social media links because we are supposed to have a list of social media links, so it makes more sense to have all the links inside a list element like the `<ul>`, this will keep our code more semantic, see the example below 👇 

```
<ul>
   <li>
       <a href="#" title="icons"><i class="fab fa-github"></i></a>
   </li>
    <li>
       <a href="#" title="icons"><i class="fab fa-linkedin-in"></i></a>
   </li>
</ul>
```

2021-09-15 19:48 UTC, barackm commented on css/styles.css
> +  width: 375px;
- [ ] It is not a good idea to specify the width in the body, and remember we are designing the portfolio using the [mobile-first approach](https://smartbear.com/learn/performance-monitoring/what-is-mobile-first/#:~:text=Mobile%20First%20Approach%20refers%20to,the%20design%20for%20mobile%20afterwards.), which means by default without having media queries or fixed width, the website should be responsive for the mobile devices if you want to see the result you can either minimize the window of your navigator or open the developer tools and toggle the device toolbar. if you are using chrome, you can follow [this tutorial](https://www.ibm.com/docs/en/rtw/9.2.0?topic=tests-recording-test-google-chrome-device-mode) on how to toggle the device toolbar 😉

2021-09-15 19:48 UTC, barackm commented on index.html
> +    <title>Document</title>
- [ ] I think it can be a good idea to give a descriptive title to your web page to keep the HTML code more semantic,  instead of `<title>Document</title>` you can have `<title>Your name</title>` 😉

2021-09-16 09:10 UTC, DanteAlonsoHT approved these changes
<h1>Status: Approve 🥇 ✔</h1>
Hi @Meri-MG, 

### Your project is complete!  I strongly recommend you to do all Optional Changes Required before merging it :shipit: 
## Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

<img src="https://media.giphy.com/media/aNqEFrYVnsS52/giphy.gif" width="100%">

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-16 09:10 UTC, DanteAlonsoHT commented on README.md
> +
- [ ] [OPTIONAL] Please add the License to your repository, if you would like to use MIT License, you can use the next text:
```
This project is [MIT](https://mit-license.org/) licensed.
```

2021-09-16 09:10 UTC, DanteAlonsoHT commented on index.html
> +</section>
- [ ] [OPTIONAL] Please fix the indentation in your HTML code to make it more professional and easy to read 😉

2021-09-16 09:10 UTC, DanteAlonsoHT commented on test.md
> +This file should be ignored by git.
- [ ] [OPTIONAL] Please, remove this file, it was only a test for your `.gitignore` file in the first project, feel free to remove it from your Github repository 😉

2021-09-16 09:37 UTC, merged